---
- name: Search schema
  ansible.builtin.command: ldapsearch -Y EXTERNAL -H ldapi:/// -b cn=schema,cn=config
  register: schema

- name: Verify and modify ldap schema
  block:
    - name: Modify schema
      ansible.builtin.command: ldapadd -Y EXTERNAL -H ldapi:/// -f addpubkeys.ldif
      register: Schema_modify
  when: schema is not search ("ssh")
