---
- name: Change sshd config
  ansible.builtin.blockinfile:
    path: "/etc/ssh/sshd_config"
    block: "{{ lookup('template', 'ssh_config') }}"

- name: Change sssd config
  ansible.builtin.lineinfile:
    path: /etc/sssd/sssd.conf
    backrefs: true
    regexp: '^(services = nss, pam,autofs)$'
    line: '\1 ,ssh'

- name: Restart sssd and sshd
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - sssd.service
    - sshd.service
